/**
 * MagicInfo Server V4.1 - REST API
 * MagicInfo Server V4.1 - REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MagicInfoServerV41RestApi) {
      root.MagicInfoServerV41RestApi = {};
    }
    root.MagicInfoServerV41RestApi.DeviceTimeHolidayResource = factory(root.MagicInfoServerV41RestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeviceTimeHolidayResource model module.
   * @module model/DeviceTimeHolidayResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeviceTimeHolidayResource</code>.
   * @alias module:model/DeviceTimeHolidayResource
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>DeviceTimeHolidayResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceTimeHolidayResource} obj Optional instance to populate.
   * @return {module:model/DeviceTimeHolidayResource} The populated <code>DeviceTimeHolidayResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('command')) {
        obj['command'] = ApiClient.convertToType(data['command'], 'String');
      }
      if (data.hasOwnProperty('day1')) {
        obj['day1'] = ApiClient.convertToType(data['day1'], 'String');
      }
      if (data.hasOwnProperty('day2')) {
        obj['day2'] = ApiClient.convertToType(data['day2'], 'String');
      }
      if (data.hasOwnProperty('deviceId')) {
        obj['deviceId'] = ApiClient.convertToType(data['deviceId'], 'String');
      }
      if (data.hasOwnProperty('holidaySeq')) {
        obj['holidaySeq'] = ApiClient.convertToType(data['holidaySeq'], 'Number');
      }
      if (data.hasOwnProperty('month1')) {
        obj['month1'] = ApiClient.convertToType(data['month1'], 'String');
      }
      if (data.hasOwnProperty('month2')) {
        obj['month2'] = ApiClient.convertToType(data['month2'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} command
   */
  exports.prototype['command'] = undefined;
  /**
   * @member {String} day1
   */
  exports.prototype['day1'] = undefined;
  /**
   * @member {String} day2
   */
  exports.prototype['day2'] = undefined;
  /**
   * @member {String} deviceId
   */
  exports.prototype['deviceId'] = undefined;
  /**
   * @member {Number} holidaySeq
   */
  exports.prototype['holidaySeq'] = undefined;
  /**
   * @member {String} month1
   */
  exports.prototype['month1'] = undefined;
  /**
   * @member {String} month2
   */
  exports.prototype['month2'] = undefined;



  return exports;
}));


