/**
 * MagicInfo Server V4 REST API
 * MagicInfo Server V4 REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MagicInfoServerV4RestApi) {
      root.MagicInfoServerV4RestApi = {};
    }
    root.MagicInfoServerV4RestApi.ContentScheduleItemResource = factory(root.MagicInfoServerV4RestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContentScheduleItemResource model module.
   * @module model/ContentScheduleItemResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ContentScheduleItemResource</code>.
   * @alias module:model/ContentScheduleItemResource
   * @class
   */
  var exports = function() {
    var _this = this;





















  };

  /**
   * Constructs a <code>ContentScheduleItemResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentScheduleItemResource} obj Optional instance to populate.
   * @return {module:model/ContentScheduleItemResource} The populated <code>ContentScheduleItemResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('channelNo')) {
        obj['channelNo'] = ApiClient.convertToType(data['channelNo'], 'Number');
      }
      if (data.hasOwnProperty('cifsSlideTime')) {
        obj['cifsSlideTime'] = ApiClient.convertToType(data['cifsSlideTime'], 'String');
      }
      if (data.hasOwnProperty('contentId')) {
        obj['contentId'] = ApiClient.convertToType(data['contentId'], 'String');
      }
      if (data.hasOwnProperty('contentName')) {
        obj['contentName'] = ApiClient.convertToType(data['contentName'], 'String');
      }
      if (data.hasOwnProperty('contentType')) {
        obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
      }
      if (data.hasOwnProperty('frameId')) {
        obj['frameId'] = ApiClient.convertToType(data['frameId'], 'String');
      }
      if (data.hasOwnProperty('frameIndex')) {
        obj['frameIndex'] = ApiClient.convertToType(data['frameIndex'], 'String');
      }
      if (data.hasOwnProperty('inputSource')) {
        obj['inputSource'] = ApiClient.convertToType(data['inputSource'], 'String');
      }
      if (data.hasOwnProperty('isSync')) {
        obj['isSync'] = ApiClient.convertToType(data['isSync'], 'String');
      }
      if (data.hasOwnProperty('monthday')) {
        obj['monthday'] = ApiClient.convertToType(data['monthday'], 'String');
      }
      if (data.hasOwnProperty('playerMode')) {
        obj['playerMode'] = ApiClient.convertToType(data['playerMode'], 'String');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
      }
      if (data.hasOwnProperty('repeatType')) {
        obj['repeatType'] = ApiClient.convertToType(data['repeatType'], 'String');
      }
      if (data.hasOwnProperty('safetyLock')) {
        obj['safetyLock'] = ApiClient.convertToType(data['safetyLock'], 'String');
      }
      if (data.hasOwnProperty('scheduleType')) {
        obj['scheduleType'] = ApiClient.convertToType(data['scheduleType'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'String');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
      }
      if (data.hasOwnProperty('stopDate')) {
        obj['stopDate'] = ApiClient.convertToType(data['stopDate'], 'String');
      }
      if (data.hasOwnProperty('weekdays')) {
        obj['weekdays'] = ApiClient.convertToType(data['weekdays'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} channelNo
   */
  exports.prototype['channelNo'] = undefined;
  /**
   * @member {String} cifsSlideTime
   */
  exports.prototype['cifsSlideTime'] = undefined;
  /**
   * @member {String} contentId
   */
  exports.prototype['contentId'] = undefined;
  /**
   * @member {String} contentName
   */
  exports.prototype['contentName'] = undefined;
  /**
   * @member {String} contentType
   */
  exports.prototype['contentType'] = undefined;
  /**
   * @member {String} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {String} frameId
   */
  exports.prototype['frameId'] = undefined;
  /**
   * @member {String} frameIndex
   */
  exports.prototype['frameIndex'] = undefined;
  /**
   * @member {String} inputSource
   */
  exports.prototype['inputSource'] = undefined;
  /**
   * @member {String} isSync
   */
  exports.prototype['isSync'] = undefined;
  /**
   * @member {String} monthday
   */
  exports.prototype['monthday'] = undefined;
  /**
   * @member {String} playerMode
   */
  exports.prototype['playerMode'] = undefined;
  /**
   * @member {Number} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * @member {String} repeatType
   */
  exports.prototype['repeatType'] = undefined;
  /**
   * @member {String} safetyLock
   */
  exports.prototype['safetyLock'] = undefined;
  /**
   * @member {String} scheduleType
   */
  exports.prototype['scheduleType'] = undefined;
  /**
   * @member {String} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {String} startTime
   */
  exports.prototype['startTime'] = undefined;
  /**
   * @member {String} stopDate
   */
  exports.prototype['stopDate'] = undefined;
  /**
   * @member {String} weekdays
   */
  exports.prototype['weekdays'] = undefined;



  return exports;
}));


