/**
 * magic info api
 * magic info api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MagicInfoApi) {
      root.MagicInfoApi = {};
    }
    root.MagicInfoApi.ContentFilter = factory(root.MagicInfoApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContentFilter model module.
   * @module model/ContentFilter
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ContentFilter</code>.
   * @alias module:model/ContentFilter
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>ContentFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentFilter} obj Optional instance to populate.
   * @return {module:model/ContentFilter} The populated <code>ContentFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
      if (data.hasOwnProperty('deviceType')) {
        obj['deviceType'] = ApiClient.convertToType(data['deviceType'], 'String');
      }
      if (data.hasOwnProperty('deviceTypeVersion')) {
        obj['deviceTypeVersion'] = ApiClient.convertToType(data['deviceTypeVersion'], 'String');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
      }
      if (data.hasOwnProperty('groupType')) {
        obj['groupType'] = ApiClient.convertToType(data['groupType'], 'String');
      }
      if (data.hasOwnProperty('mediaType')) {
        obj['mediaType'] = ApiClient.convertToType(data['mediaType'], 'String');
      }
      if (data.hasOwnProperty('mediaTypeFilter')) {
        obj['mediaTypeFilter'] = ApiClient.convertToType(data['mediaTypeFilter'], 'String');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('searchText')) {
        obj['searchText'] = ApiClient.convertToType(data['searchText'], 'String');
      }
      if (data.hasOwnProperty('selectId')) {
        obj['selectId'] = ApiClient.convertToType(data['selectId'], 'String');
      }
      if (data.hasOwnProperty('sortColumn')) {
        obj['sortColumn'] = ApiClient.convertToType(data['sortColumn'], 'String');
      }
      if (data.hasOwnProperty('sortOrder')) {
        obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'String');
      }
      if (data.hasOwnProperty('startIndex')) {
        obj['startIndex'] = ApiClient.convertToType(data['startIndex'], 'Number');
      }
      if (data.hasOwnProperty('tag')) {
        obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} category
   */
  exports.prototype['category'] = undefined;
  /**
   * @member {String} deviceType
   */
  exports.prototype['deviceType'] = undefined;
  /**
   * @member {String} deviceTypeVersion
   */
  exports.prototype['deviceTypeVersion'] = undefined;
  /**
   * @member {String} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * @member {String} groupType
   */
  exports.prototype['groupType'] = undefined;
  /**
   * @member {String} mediaType
   */
  exports.prototype['mediaType'] = undefined;
  /**
   * @member {String} mediaTypeFilter
   */
  exports.prototype['mediaTypeFilter'] = undefined;
  /**
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * @member {String} searchText
   */
  exports.prototype['searchText'] = undefined;
  /**
   * @member {String} selectId
   */
  exports.prototype['selectId'] = undefined;
  /**
   * @member {String} sortColumn
   */
  exports.prototype['sortColumn'] = undefined;
  /**
   * @member {String} sortOrder
   */
  exports.prototype['sortOrder'] = undefined;
  /**
   * @member {Number} startIndex
   */
  exports.prototype['startIndex'] = undefined;
  /**
   * @member {String} tag
   */
  exports.prototype['tag'] = undefined;
  /**
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;



  return exports;
}));


