/**
 * magic info api
 * magic info api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MagicInfoApi) {
      root.MagicInfoApi = {};
    }
    root.MagicInfoApi.DeviceApproveResource = factory(root.MagicInfoApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeviceApproveResource model module.
   * @module model/DeviceApproveResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeviceApproveResource</code>.
   * @alias module:model/DeviceApproveResource
   * @class
   * @param calDate {String} 
   * @param deviceId {String} 
   * @param deviceName {String} 
   * @param deviceType {String} 
   * @param groupId {String} 
   * @param hasChild {String} 
   */
  var exports = function(calDate, deviceId, deviceName, deviceType, groupId, hasChild) {
    var _this = this;

    _this['calDate'] = calDate;

    _this['deviceId'] = deviceId;
    _this['deviceName'] = deviceName;
    _this['deviceType'] = deviceType;
    _this['groupId'] = groupId;
    _this['hasChild'] = hasChild;




  };

  /**
   * Constructs a <code>DeviceApproveResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceApproveResource} obj Optional instance to populate.
   * @return {module:model/DeviceApproveResource} The populated <code>DeviceApproveResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('calDate')) {
        obj['calDate'] = ApiClient.convertToType(data['calDate'], 'String');
      }
      if (data.hasOwnProperty('childCnt')) {
        obj['childCnt'] = ApiClient.convertToType(data['childCnt'], 'String');
      }
      if (data.hasOwnProperty('deviceId')) {
        obj['deviceId'] = ApiClient.convertToType(data['deviceId'], 'String');
      }
      if (data.hasOwnProperty('deviceName')) {
        obj['deviceName'] = ApiClient.convertToType(data['deviceName'], 'String');
      }
      if (data.hasOwnProperty('deviceType')) {
        obj['deviceType'] = ApiClient.convertToType(data['deviceType'], 'String');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
      }
      if (data.hasOwnProperty('hasChild')) {
        obj['hasChild'] = ApiClient.convertToType(data['hasChild'], 'String');
      }
      if (data.hasOwnProperty('ipAddress')) {
        obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('organization')) {
        obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
      }
      if (data.hasOwnProperty('slaveNumber')) {
        obj['slaveNumber'] = ApiClient.convertToType(data['slaveNumber'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} calDate
   */
  exports.prototype['calDate'] = undefined;
  /**
   * @member {String} childCnt
   */
  exports.prototype['childCnt'] = undefined;
  /**
   * @member {String} deviceId
   */
  exports.prototype['deviceId'] = undefined;
  /**
   * @member {String} deviceName
   */
  exports.prototype['deviceName'] = undefined;
  /**
   * @member {String} deviceType
   */
  exports.prototype['deviceType'] = undefined;
  /**
   * @member {String} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * @member {String} hasChild
   */
  exports.prototype['hasChild'] = undefined;
  /**
   * @member {String} ipAddress
   */
  exports.prototype['ipAddress'] = undefined;
  /**
   * @member {String} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {String} organization
   */
  exports.prototype['organization'] = undefined;
  /**
   * @member {String} slaveNumber
   */
  exports.prototype['slaveNumber'] = undefined;



  return exports;
}));


