/**
 * MagicInfo Server V4.1 - REST API
 * MagicInfo Server V4.1 - REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MagicInfoServerV41RestApi) {
      root.MagicInfoServerV41RestApi = {};
    }
    root.MagicInfoServerV41RestApi.DeviceSecurityConfResource = factory(root.MagicInfoServerV41RestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeviceSecurityConfResource model module.
   * @module model/DeviceSecurityConfResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeviceSecurityConfResource</code>.
   * @alias module:model/DeviceSecurityConfResource
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>DeviceSecurityConfResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceSecurityConfResource} obj Optional instance to populate.
   * @return {module:model/DeviceSecurityConfResource} The populated <code>DeviceSecurityConfResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('isInitSecurity')) {
        obj['isInitSecurity'] = ApiClient.convertToType(data['isInitSecurity'], 'Boolean');
      }
      if (data.hasOwnProperty('miscAllLock')) {
        obj['miscAllLock'] = ApiClient.convertToType(data['miscAllLock'], 'Number');
      }
      if (data.hasOwnProperty('miscBlockNetworkConnection')) {
        obj['miscBlockNetworkConnection'] = ApiClient.convertToType(data['miscBlockNetworkConnection'], 'Number');
      }
      if (data.hasOwnProperty('miscBlockUsbPort')) {
        obj['miscBlockUsbPort'] = ApiClient.convertToType(data['miscBlockUsbPort'], 'Number');
      }
      if (data.hasOwnProperty('miscPanelLock')) {
        obj['miscPanelLock'] = ApiClient.convertToType(data['miscPanelLock'], 'Number');
      }
      if (data.hasOwnProperty('miscRemocon')) {
        obj['miscRemocon'] = ApiClient.convertToType(data['miscRemocon'], 'Number');
      }
      if (data.hasOwnProperty('miscWhiteList')) {
        obj['miscWhiteList'] = ApiClient.convertToType(data['miscWhiteList'], 'String');
      }
      if (data.hasOwnProperty('mntSafetyLock')) {
        obj['mntSafetyLock'] = ApiClient.convertToType(data['mntSafetyLock'], 'Number');
      }
      if (data.hasOwnProperty('touchControlLock')) {
        obj['touchControlLock'] = ApiClient.convertToType(data['touchControlLock'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} isInitSecurity
   */
  exports.prototype['isInitSecurity'] = undefined;
  /**
   * @member {Number} miscAllLock
   */
  exports.prototype['miscAllLock'] = undefined;
  /**
   * @member {Number} miscBlockNetworkConnection
   */
  exports.prototype['miscBlockNetworkConnection'] = undefined;
  /**
   * @member {Number} miscBlockUsbPort
   */
  exports.prototype['miscBlockUsbPort'] = undefined;
  /**
   * @member {Number} miscPanelLock
   */
  exports.prototype['miscPanelLock'] = undefined;
  /**
   * @member {Number} miscRemocon
   */
  exports.prototype['miscRemocon'] = undefined;
  /**
   * @member {String} miscWhiteList
   */
  exports.prototype['miscWhiteList'] = undefined;
  /**
   * @member {Number} mntSafetyLock
   */
  exports.prototype['mntSafetyLock'] = undefined;
  /**
   * @member {Number} touchControlLock
   */
  exports.prototype['touchControlLock'] = undefined;



  return exports;
}));


