/**
 * MagicInfo Server V4.1 REST API
 * MagicInfo Server V4.1 REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MagicInfoServerV41RestApi) {
      root.MagicInfoServerV41RestApi = {};
    }
    root.MagicInfoServerV41RestApi.EnvironmentPriorityFilter = factory(root.MagicInfoServerV41RestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EnvironmentPriorityFilter model module.
   * @module model/EnvironmentPriorityFilter
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EnvironmentPriorityFilter</code>.
   * @alias module:model/EnvironmentPriorityFilter
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>EnvironmentPriorityFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EnvironmentPriorityFilter} obj Optional instance to populate.
   * @return {module:model/EnvironmentPriorityFilter} The populated <code>EnvironmentPriorityFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('contentInfoDashboard')) {
        obj['contentInfoDashboard'] = ApiClient.convertToType(data['contentInfoDashboard'], 'Number');
      }
      if (data.hasOwnProperty('deviceInfoDashboard')) {
        obj['deviceInfoDashboard'] = ApiClient.convertToType(data['deviceInfoDashboard'], 'Number');
      }
      if (data.hasOwnProperty('noticeInfoDashboard')) {
        obj['noticeInfoDashboard'] = ApiClient.convertToType(data['noticeInfoDashboard'], 'Number');
      }
      if (data.hasOwnProperty('playlistInfoDashboard')) {
        obj['playlistInfoDashboard'] = ApiClient.convertToType(data['playlistInfoDashboard'], 'Number');
      }
      if (data.hasOwnProperty('scheduleInfoDashboard')) {
        obj['scheduleInfoDashboard'] = ApiClient.convertToType(data['scheduleInfoDashboard'], 'Number');
      }
      if (data.hasOwnProperty('signInfoDashboard')) {
        obj['signInfoDashboard'] = ApiClient.convertToType(data['signInfoDashboard'], 'Number');
      }
      if (data.hasOwnProperty('storageInfoDashboard')) {
        obj['storageInfoDashboard'] = ApiClient.convertToType(data['storageInfoDashboard'], 'Number');
      }
      if (data.hasOwnProperty('userInfoDashboard')) {
        obj['userInfoDashboard'] = ApiClient.convertToType(data['userInfoDashboard'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} contentInfoDashboard
   */
  exports.prototype['contentInfoDashboard'] = undefined;
  /**
   * @member {Number} deviceInfoDashboard
   */
  exports.prototype['deviceInfoDashboard'] = undefined;
  /**
   * @member {Number} noticeInfoDashboard
   */
  exports.prototype['noticeInfoDashboard'] = undefined;
  /**
   * @member {Number} playlistInfoDashboard
   */
  exports.prototype['playlistInfoDashboard'] = undefined;
  /**
   * @member {Number} scheduleInfoDashboard
   */
  exports.prototype['scheduleInfoDashboard'] = undefined;
  /**
   * @member {Number} signInfoDashboard
   */
  exports.prototype['signInfoDashboard'] = undefined;
  /**
   * @member {Number} storageInfoDashboard
   */
  exports.prototype['storageInfoDashboard'] = undefined;
  /**
   * @member {Number} userInfoDashboard
   */
  exports.prototype['userInfoDashboard'] = undefined;



  return exports;
}));


