/**
 * MagicInfo Server V4x REST API
 * MagicInfo Server V4x REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MagicInfoServerV4xRestApi) {
      root.MagicInfoServerV4xRestApi = {};
    }
    root.MagicInfoServerV4xRestApi.ScheduleFilter = factory(root.MagicInfoServerV4xRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ScheduleFilter model module.
   * @module model/ScheduleFilter
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ScheduleFilter</code>.
   * @alias module:model/ScheduleFilter
   * @class
   */
  var exports = function() {
    var _this = this;






















  };

  /**
   * Constructs a <code>ScheduleFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScheduleFilter} obj Optional instance to populate.
   * @return {module:model/ScheduleFilter} The populated <code>ScheduleFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deviceType')) {
        obj['deviceType'] = ApiClient.convertToType(data['deviceType'], 'String');
      }
      if (data.hasOwnProperty('endModifiedDate')) {
        obj['endModifiedDate'] = ApiClient.convertToType(data['endModifiedDate'], 'String');
      }
      if (data.hasOwnProperty('frameCount')) {
        obj['frameCount'] = ApiClient.convertToType(data['frameCount'], 'String');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
      }
      if (data.hasOwnProperty('groupName')) {
        obj['groupName'] = ApiClient.convertToType(data['groupName'], 'String');
      }
      if (data.hasOwnProperty('groupType')) {
        obj['groupType'] = ApiClient.convertToType(data['groupType'], 'String');
      }
      if (data.hasOwnProperty('isSelect')) {
        obj['isSelect'] = ApiClient.convertToType(data['isSelect'], 'String');
      }
      if (data.hasOwnProperty('orderNumber')) {
        obj['orderNumber'] = ApiClient.convertToType(data['orderNumber'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('productType')) {
        obj['productType'] = ApiClient.convertToType(data['productType'], 'String');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], 'Number');
      }
      if (data.hasOwnProperty('scheduleType')) {
        obj['scheduleType'] = ApiClient.convertToType(data['scheduleType'], 'String');
      }
      if (data.hasOwnProperty('searchContentIds')) {
        obj['searchContentIds'] = ApiClient.convertToType(data['searchContentIds'], 'String');
      }
      if (data.hasOwnProperty('searchDevGroupIds')) {
        obj['searchDevGroupIds'] = ApiClient.convertToType(data['searchDevGroupIds'], 'String');
      }
      if (data.hasOwnProperty('searchId')) {
        obj['searchId'] = ApiClient.convertToType(data['searchId'], 'String');
      }
      if (data.hasOwnProperty('searchText')) {
        obj['searchText'] = ApiClient.convertToType(data['searchText'], 'String');
      }
      if (data.hasOwnProperty('selectId')) {
        obj['selectId'] = ApiClient.convertToType(data['selectId'], 'String');
      }
      if (data.hasOwnProperty('sortColumn')) {
        obj['sortColumn'] = ApiClient.convertToType(data['sortColumn'], 'String');
      }
      if (data.hasOwnProperty('sortOrder')) {
        obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'String');
      }
      if (data.hasOwnProperty('startIndex')) {
        obj['startIndex'] = ApiClient.convertToType(data['startIndex'], 'Number');
      }
      if (data.hasOwnProperty('startModifiedDate')) {
        obj['startModifiedDate'] = ApiClient.convertToType(data['startModifiedDate'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} deviceType
   */
  exports.prototype['deviceType'] = undefined;
  /**
   * @member {String} endModifiedDate
   */
  exports.prototype['endModifiedDate'] = undefined;
  /**
   * @member {String} frameCount
   */
  exports.prototype['frameCount'] = undefined;
  /**
   * @member {String} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * @member {String} groupName
   */
  exports.prototype['groupName'] = undefined;
  /**
   * @member {String} groupType
   */
  exports.prototype['groupType'] = undefined;
  /**
   * @member {String} isSelect
   */
  exports.prototype['isSelect'] = undefined;
  /**
   * @member {Number} orderNumber
   */
  exports.prototype['orderNumber'] = undefined;
  /**
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * @member {String} productType
   */
  exports.prototype['productType'] = undefined;
  /**
   * @member {Number} results
   */
  exports.prototype['results'] = undefined;
  /**
   * @member {String} scheduleType
   */
  exports.prototype['scheduleType'] = undefined;
  /**
   * @member {String} searchContentIds
   */
  exports.prototype['searchContentIds'] = undefined;
  /**
   * @member {String} searchDevGroupIds
   */
  exports.prototype['searchDevGroupIds'] = undefined;
  /**
   * @member {String} searchId
   */
  exports.prototype['searchId'] = undefined;
  /**
   * @member {String} searchText
   */
  exports.prototype['searchText'] = undefined;
  /**
   * @member {String} selectId
   */
  exports.prototype['selectId'] = undefined;
  /**
   * @member {String} sortColumn
   */
  exports.prototype['sortColumn'] = undefined;
  /**
   * @member {String} sortOrder
   */
  exports.prototype['sortOrder'] = undefined;
  /**
   * @member {Number} startIndex
   */
  exports.prototype['startIndex'] = undefined;
  /**
   * @member {String} startModifiedDate
   */
  exports.prototype['startModifiedDate'] = undefined;



  return exports;
}));


