/**
 * MagicInfo Server V4x REST API
 * MagicInfo Server V4x REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MagicInfoServerV4xRestApi);
  }
}(this, function(expect, MagicInfoServerV4xRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MagicInfoServerV4xRestApi.DeviceDownloadServerResource();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeviceDownloadServerResource', function() {
    it('should create an instance of DeviceDownloadServerResource', function() {
      // uncomment below and update the code to test DeviceDownloadServerResource
      //var instane = new MagicInfoServerV4xRestApi.DeviceDownloadServerResource();
      //expect(instance).to.be.a(MagicInfoServerV4xRestApi.DeviceDownloadServerResource);
    });

    it('should have the property ftpPort (base name: "ftpPort")', function() {
      // uncomment below and update the code to test the property ftpPort
      //var instane = new MagicInfoServerV4xRestApi.DeviceDownloadServerResource();
      //expect(instance).to.be();
    });

    it('should have the property hostName (base name: "hostName")', function() {
      // uncomment below and update the code to test the property hostName
      //var instane = new MagicInfoServerV4xRestApi.DeviceDownloadServerResource();
      //expect(instance).to.be();
    });

    it('should have the property ipAddress (base name: "ipAddress")', function() {
      // uncomment below and update the code to test the property ipAddress
      //var instane = new MagicInfoServerV4xRestApi.DeviceDownloadServerResource();
      //expect(instance).to.be();
    });

    it('should have the property selected (base name: "selected")', function() {
      // uncomment below and update the code to test the property selected
      //var instane = new MagicInfoServerV4xRestApi.DeviceDownloadServerResource();
      //expect(instance).to.be();
    });

  });

}));
