/**
 * MagicInfo Server V4 REST API
 * MagicInfo Server V4 REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MagicInfoServerV4RestApi);
  }
}(this, function(expect, MagicInfoServerV4RestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeviceTimeClockConf', function() {
    it('should create an instance of DeviceTimeClockConf', function() {
      // uncomment below and update the code to test DeviceTimeClockConf
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be.a(MagicInfoServerV4RestApi.DeviceTimeClockConf);
    });

    it('should have the property clockAmpm (base name: "clockAmpm")', function() {
      // uncomment below and update the code to test the property clockAmpm
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property clockDay (base name: "clockDay")', function() {
      // uncomment below and update the code to test the property clockDay
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property clockH (base name: "clockH")', function() {
      // uncomment below and update the code to test the property clockH
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property clockM (base name: "clockM")', function() {
      // uncomment below and update the code to test the property clockM
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property clockMon (base name: "clockMon")', function() {
      // uncomment below and update the code to test the property clockMon
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property clockY1 (base name: "clockY1")', function() {
      // uncomment below and update the code to test the property clockY1
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property clockY2 (base name: "clockY2")', function() {
      // uncomment below and update the code to test the property clockY2
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property deviceId (base name: "deviceId")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property deviceModelCode (base name: "deviceModelCode")', function() {
      // uncomment below and update the code to test the property deviceModelCode
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property deviceModelName (base name: "deviceModelName")', function() {
      // uncomment below and update the code to test the property deviceModelName
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

    it('should have the property deviceName (base name: "deviceName")', function() {
      // uncomment below and update the code to test the property deviceName
      //var instane = new MagicInfoServerV4RestApi.DeviceTimeClockConf();
      //expect(instance).to.be();
    });

  });

}));
