/**
 * magic info api
 * magic info api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MagicInfoApi);
  }
}(this, function(expect, MagicInfoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MagicInfoApi.ScheduleFilter();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScheduleFilter', function() {
    it('should create an instance of ScheduleFilter', function() {
      // uncomment below and update the code to test ScheduleFilter
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be.a(MagicInfoApi.ScheduleFilter);
    });

    it('should have the property deviceType (base name: "deviceType")', function() {
      // uncomment below and update the code to test the property deviceType
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property endModifiedDate (base name: "endModifiedDate")', function() {
      // uncomment below and update the code to test the property endModifiedDate
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property frameCount (base name: "frameCount")', function() {
      // uncomment below and update the code to test the property frameCount
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property groupName (base name: "groupName")', function() {
      // uncomment below and update the code to test the property groupName
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property groupType (base name: "groupType")', function() {
      // uncomment below and update the code to test the property groupType
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property isSelect (base name: "isSelect")', function() {
      // uncomment below and update the code to test the property isSelect
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property orderNumber (base name: "orderNumber")', function() {
      // uncomment below and update the code to test the property orderNumber
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "pageSize")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property productType (base name: "productType")', function() {
      // uncomment below and update the code to test the property productType
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property results (base name: "results")', function() {
      // uncomment below and update the code to test the property results
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property scheduleType (base name: "scheduleType")', function() {
      // uncomment below and update the code to test the property scheduleType
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property searchContentIds (base name: "searchContentIds")', function() {
      // uncomment below and update the code to test the property searchContentIds
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property searchDevGroupIds (base name: "searchDevGroupIds")', function() {
      // uncomment below and update the code to test the property searchDevGroupIds
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property searchId (base name: "searchId")', function() {
      // uncomment below and update the code to test the property searchId
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property searchText (base name: "searchText")', function() {
      // uncomment below and update the code to test the property searchText
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property selectId (base name: "selectId")', function() {
      // uncomment below and update the code to test the property selectId
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property sortColumn (base name: "sortColumn")', function() {
      // uncomment below and update the code to test the property sortColumn
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property sortOrder (base name: "sortOrder")', function() {
      // uncomment below and update the code to test the property sortOrder
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property startIndex (base name: "startIndex")', function() {
      // uncomment below and update the code to test the property startIndex
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

    it('should have the property startModifiedDate (base name: "startModifiedDate")', function() {
      // uncomment below and update the code to test the property startModifiedDate
      //var instane = new MagicInfoApi.ScheduleFilter();
      //expect(instance).to.be();
    });

  });

}));
