/**
 * magic info api
 * magic info api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MagicInfoApi);
  }
}(this, function(expect, MagicInfoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MagicInfoApi.DeviceControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeviceControllerApi', function() {
    describe('approveDeviceUsingPUT', function() {
      it('should call approveDeviceUsingPUT successfully', function(done) {
        //uncomment below and update the code to test approveDeviceUsingPUT
        //instance.approveDeviceUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDeviceUsingDELETE', function() {
      it('should call deleteDeviceUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteDeviceUsingDELETE
        //instance.deleteDeviceUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filterDeviceListUsingPOST', function() {
      it('should call filterDeviceListUsingPOST successfully', function(done) {
        //uncomment below and update the code to test filterDeviceListUsingPOST
        //instance.filterDeviceListUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCabinetListUsingPOST1', function() {
      it('should call getCabinetListUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test getCabinetListUsingPOST1
        //instance.getCabinetListUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentStatusDisplayUsingGET1', function() {
      it('should call getCurrentStatusDisplayUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getCurrentStatusDisplayUsingGET1
        //instance.getCurrentStatusDisplayUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentStatusDisplayUsingGET3', function() {
      it('should call getCurrentStatusDisplayUsingGET3 successfully', function(done) {
        //uncomment below and update the code to test getCurrentStatusDisplayUsingGET3
        //instance.getCurrentStatusDisplayUsingGET3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentStatusSecurityUsingGET1', function() {
      it('should call getCurrentStatusSecurityUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getCurrentStatusSecurityUsingGET1
        //instance.getCurrentStatusSecurityUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentStatusSecurityUsingGET3', function() {
      it('should call getCurrentStatusSecurityUsingGET3 successfully', function(done) {
        //uncomment below and update the code to test getCurrentStatusSecurityUsingGET3
        //instance.getCurrentStatusSecurityUsingGET3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentStatusTimeUsingGET', function() {
      it('should call getCurrentStatusTimeUsingGET successfully', function(done) {
        //uncomment below and update the code to test getCurrentStatusTimeUsingGET
        //instance.getCurrentStatusTimeUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentStatusTimeUsingGET3', function() {
      it('should call getCurrentStatusTimeUsingGET3 successfully', function(done) {
        //uncomment below and update the code to test getCurrentStatusTimeUsingGET3
        //instance.getCurrentStatusTimeUsingGET3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDashboardDeviceInfoUsingGET', function() {
      it('should call getDashboardDeviceInfoUsingGET successfully', function(done) {
        //uncomment below and update the code to test getDashboardDeviceInfoUsingGET
        //instance.getDashboardDeviceInfoUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDeviceUsingGET1', function() {
      it('should call getDeviceUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getDeviceUsingGET1
        //instance.getDeviceUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDisplayControlInfoUsingGET1', function() {
      it('should call getDisplayControlInfoUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getDisplayControlInfoUsingGET1
        //instance.getDisplayControlInfoUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGeneralInfoUsingGET1', function() {
      it('should call getGeneralInfoUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getGeneralInfoUsingGET1
        //instance.getGeneralInfoUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSecurityControlInfoUsingGET1', function() {
      it('should call getSecurityControlInfoUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getSecurityControlInfoUsingGET1
        //instance.getSecurityControlInfoUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSetupInfoUsingGET1', function() {
      it('should call getSetupInfoUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getSetupInfoUsingGET1
        //instance.getSetupInfoUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTimeInfoUsingGET', function() {
      it('should call getTimeInfoUsingGET successfully', function(done) {
        //uncomment below and update the code to test getTimeInfoUsingGET
        //instance.getTimeInfoUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUpdatedDisplayInfoResultUsingGET1', function() {
      it('should call getUpdatedDisplayInfoResultUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getUpdatedDisplayInfoResultUsingGET1
        //instance.getUpdatedDisplayInfoResultUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUpdatedGeneralInfoResultUsingGET', function() {
      it('should call getUpdatedGeneralInfoResultUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUpdatedGeneralInfoResultUsingGET
        //instance.getUpdatedGeneralInfoResultUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUpdatedSetupInfoResultUsingGET1', function() {
      it('should call getUpdatedSetupInfoResultUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getUpdatedSetupInfoResultUsingGET1
        //instance.getUpdatedSetupInfoResultUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUpdatedTimeInfoResultUsingGET', function() {
      it('should call getUpdatedTimeInfoResultUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUpdatedTimeInfoResultUsingGET
        //instance.getUpdatedTimeInfoResultUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllDeviceUsingGET', function() {
      it('should call listAllDeviceUsingGET successfully', function(done) {
        //uncomment below and update the code to test listAllDeviceUsingGET
        //instance.listAllDeviceUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('moveDeviceUsingPUT', function() {
      it('should call moveDeviceUsingPUT successfully', function(done) {
        //uncomment below and update the code to test moveDeviceUsingPUT
        //instance.moveDeviceUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('startRmServerVncUsingGET', function() {
      it('should call startRmServerVncUsingGET successfully', function(done) {
        //uncomment below and update the code to test startRmServerVncUsingGET
        //instance.startRmServerVncUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('stopRmServerVncUsingGET', function() {
      it('should call stopRmServerVncUsingGET successfully', function(done) {
        //uncomment below and update the code to test stopRmServerVncUsingGET
        //instance.stopRmServerVncUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCabinetInfoUsingPUT', function() {
      it('should call updateCabinetInfoUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateCabinetInfoUsingPUT
        //instance.updateCabinetInfoUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDisplayInfoUsingPUT', function() {
      it('should call updateDisplayInfoUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateDisplayInfoUsingPUT
        //instance.updateDisplayInfoUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateGeneralInfoUsingPUT', function() {
      it('should call updateGeneralInfoUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateGeneralInfoUsingPUT
        //instance.updateGeneralInfoUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateGeneralUsingPUT', function() {
      it('should call updateGeneralUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateGeneralUsingPUT
        //instance.updateGeneralUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSecurityInfoUsingPUT', function() {
      it('should call updateSecurityInfoUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateSecurityInfoUsingPUT
        //instance.updateSecurityInfoUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSetupInfoUsingPUT', function() {
      it('should call updateSetupInfoUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateSetupInfoUsingPUT
        //instance.updateSetupInfoUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTimeInfoUsingPUT1', function() {
      it('should call updateTimeInfoUsingPUT1 successfully', function(done) {
        //uncomment below and update the code to test updateTimeInfoUsingPUT1
        //instance.updateTimeInfoUsingPUT1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
